apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hospitalmanagement-app
  template:
    metadata:
      labels:
        app: hospitalmanagement-app
    spec:
      containers:
      - name: hospitalmanagment-container
        image: hospitalmanagement:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hospitalmanagment-service
spec:
  selector:
    app: hospitalmanagment-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
